version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:736104672109:task-definition/taskDef:2"
        LoadBalancerInfo:
          ContainerName: "demoContainer"
          ContainerPort: "8080"
        PlatformVersion: "LATEST"
